/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_giaodien;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class User_information extends javax.swing.JFrame {

    /**
     * Creates new form User_information
     */
    public User_information() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonXemTen = new javax.swing.JButton();
        ButtonXemMatkhau = new javax.swing.JButton();
        TextTen = new javax.swing.JTextField();
        TextMatkhau = new javax.swing.JTextField();
        ButtonDangXuat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ButtonBack = new javax.swing.JButton();
        ButtonChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài Tập Lớn Nhóm 13");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_giaodien/icon.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Thông TIn Người Dùng");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Tên ");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Mật Khẩu ");

        ButtonXemTen.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        ButtonXemTen.setText("Xem");
        ButtonXemTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXemTenActionPerformed(evt);
            }
        });

        ButtonXemMatkhau.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        ButtonXemMatkhau.setText("Xem");
        ButtonXemMatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXemMatkhauActionPerformed(evt);
            }
        });

        TextTen.setText("xxxxxx");

        TextMatkhau.setText("******");

        ButtonDangXuat.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        ButtonDangXuat.setForeground(new java.awt.Color(255, 0, 0));
        ButtonDangXuat.setText("Đăng Xuất");
        ButtonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDangXuatActionPerformed(evt);
            }
        });

        ButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_giaodien/quaylai.jpg"))); // NOI18N
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonChange.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        ButtonChange.setForeground(new java.awt.Color(255, 0, 51));
        ButtonChange.setText("Change");
        ButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextMatkhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonXemMatkhau))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonXemTen))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(ButtonDangXuat)
                        .addGap(26, 26, 26)
                        .addComponent(ButtonChange))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(ButtonBack))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonXemTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ButtonXemMatkhau))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDangXuat)
                    .addComponent(ButtonChange))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
        if (ButtonChange.getText().equals("Xác Nhận")) {
            JOptionPane.showMessageDialog(this, "Error\n" + "Bạn cần Xác Nhận thay đổi!");
            return;
        }
        dispose();
        App_interface inter = new App_interface();
        inter.setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDangXuatActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_ButtonDangXuatActionPerformed

    private void ButtonXemTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXemTenActionPerformed
        // TODO add your handling code here:
        if (ButtonChange.getText().equals("Xác Nhận")) {
            TextTen.requestFocus();
            return;
        }
        String name = "name";
        if (ButtonXemTen.getText().equals("Xem")) {
            TextTen.setText(name);
            ButtonXemTen.setText("ẩn");
        } else {
            TextTen.setText("xxxxxx");
            ButtonXemTen.setText("Xem");
        }

    }//GEN-LAST:event_ButtonXemTenActionPerformed

    private void ButtonXemMatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXemMatkhauActionPerformed
        // TODO add your handling code here:
        if (ButtonChange.getText().equals("Xác Nhận")) {
            TextMatkhau.requestFocus();
            return;
        }
        String password = "password";
        if (ButtonXemMatkhau.getText().equals("Xem")) {
            TextMatkhau.setText(password);
            ButtonXemMatkhau.setText("ẩn");
        } else {
            TextMatkhau.setText("******");
            ButtonXemMatkhau.setText("Xem");
        }
    }//GEN-LAST:event_ButtonXemMatkhauActionPerformed

    private void ButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChangeActionPerformed
        // TODO add your handling code here:
        String name = "name", pasword = "password";
        if (ButtonChange.getText().equals("Change")) {
            TextTen.setBackground(Color.yellow);
            TextMatkhau.setBackground(Color.yellow);
            TextTen.setText("");
            TextMatkhau.setText("");
            ButtonChange.setText("Xác Nhận");
            TextTen.requestFocus();
            return;
        }
        if (ButtonChange.getText().equals("Xác Nhận")) {
            if (TextTen.getText().equals("") == false) {
                name = TextTen.getText();
            }
            if (TextMatkhau.getText().equals("") == false) {
                pasword = TextMatkhau.getText();
            }
            String ten = "Tên tài khoản: " + name + "\n";
            String matKhau = "Mật khẩu tài khoản: " + pasword;
            TextTen.setBackground(Color.white);
            TextMatkhau.setBackground(Color.white);
            JOptionPane.showMessageDialog(this, ten + matKhau);
            TextTen.setText("xxxxxx");
            TextMatkhau.setText("******");
            ButtonChange.setText("Change");
            ButtonXemTen.setText("Xem");
            ButtonXemMatkhau.setText("Xem");
            return;
        }

    }//GEN-LAST:event_ButtonChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User_information().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonChange;
    private javax.swing.JButton ButtonDangXuat;
    private javax.swing.JButton ButtonXemMatkhau;
    private javax.swing.JButton ButtonXemTen;
    private javax.swing.JTextField TextMatkhau;
    private javax.swing.JTextField TextTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
